# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from GUI_Data import *
from Algorithm import *
from PyQt5.QtCore import QAbstractTableModel, Qt
from PyQt5.QtWidgets import QApplication, QTableView
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 749)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 0, 271, 51))
        self.label1.setAutoFillBackground(True)
        self.label1.setStyleSheet("\n"
"font: 87 8pt \"Arial Black\";")
        self.label1.setTextFormat(QtCore.Qt.PlainText)
        self.label1.setObjectName("label1")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-90, 50, 1261, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.TimeSelect = QtWidgets.QTimeEdit(self.centralwidget)
        self.TimeSelect.setGeometry(QtCore.QRect(20, 80, 118, 22))
        self.TimeSelect.setObjectName("TimeSelect")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(270, 60, 21, 641))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.startlab = QtWidgets.QLabel(self.centralwidget)
        self.startlab.setGeometry(QtCore.QRect(10, 160, 131, 16))
        self.startlab.setObjectName("startlab")
        self.destlab = QtWidgets.QLabel(self.centralwidget)
        self.destlab.setGeometry(QtCore.QRect(10, 290, 111, 16))
        self.destlab.setObjectName("destlab")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 440, 121, 28))
        self.pushButton.setObjectName("pushButton")
        self.resultframe = QtWidgets.QFrame(self.centralwidget)
        self.resultframe.setGeometry(QtCore.QRect(350, 140, 631, 371))
        self.resultframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resultframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resultframe.setObjectName("resultframe")
        self.tableView = QtWidgets.QTableView(self.resultframe)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 631, 371))
        self.tableView.setObjectName("tableView")
        self.cbox1 = QtWidgets.QComboBox(self.centralwidget)
        self.cbox1.setGeometry(QtCore.QRect(40, 200, 171, 51))
        self.cbox1.setObjectName("cbox1")
        self.cbox1.addItems(datalist)
        # self.cbox1.activated.connect(self.action)
        self.cbox2 = QtWidgets.QComboBox(self.centralwidget)
        self.cbox2.setGeometry(QtCore.QRect(40, 330, 171, 51))
        self.cbox2.setObjectName("cbox2")
        self.cbox2.addItems(datalist)
        # self.cbox2.activated.connect(self.action2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "London Underground Tube Guide"))
        self.startlab.setText(_translate("MainWindow", "Start Station :"))
        self.destlab.setText(_translate("MainWindow", "Destination : "))
        self.pushButton.setText(_translate("MainWindow", "FIND ROUTE"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

#Class to insert pandas dataframe to tableview
class PandasModel(QtCore.QAbstractTableModel):
    """
    Class to populate a table view with a pandas dataframe
    """
    def __init__(self, data, parent=None):
        QtCore.QAbstractTableModel.__init__(self, parent)
        self._data = data

    def rowCount(self, parent=None):
        return len(self._data.values)

    def columnCount(self, parent=None):
        return self._data.columns.size

    def data(self, index, role=QtCore.Qt.DisplayRole):
        if index.isValid():
            if role == QtCore.Qt.DisplayRole:
                return str(self._data.values[index.row()][index.column()])
        return None

    def headerData(self, col, orientation, role):
        if orientation == QtCore.Qt.Horizontal and role == QtCore.Qt.DisplayRole:
            return self._data.columns[col]
        return None





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    model = PandasModel(df5)
    tableView.setModel(model)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
